repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: trailing-whitespace
    - id: check-ast
    - id: debug-statements
    - id: end-of-file-fixer
    - id: check-docstring-first
    - id: check-added-large-files
      exclude_types: [yaml]
    - id: check-json
    - id: check-merge-conflict
    - id: check-yaml

- repo: https://github.com/codespell-project/codespell
  rev: v2.4.2
  hooks:
    - id: codespell
      exclude: >
          (?x)^(
              .*\.yaml
          )$
      args:
        - --ignore-words-list=slippy,astroid

- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.9.1
  hooks:
    - id: nbqa-check-ast
    - id: nbqa-black

- repo: https://github.com/bdice/nb-strip-paths
  rev: v0.1.0
  hooks:
    - id: nb-strip-paths

- repo: https://github.com/woodruffw/zizmor-pre-commit
  rev: v1.25.2
  hooks:
    - id: zizmor

ci:
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks

        for more information, see https://pre-commit.ci
    autofix_prs: false
    skip: []
    submodules: false
