name: Publish Glider Map of the Day

on:
  pull_request:
  schedule:
    - cron: "0 10 * * *"
  workflow_dispatch:

jobs:
  build:
    name: glider map
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Micromamba Python ${{ matrix.python-version }}
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: glider_of_the_day
          init-shell: bash
          create-args: >-
            python=${{ matrix.python-version }} --file conda-lock.yml --channel conda-forge

      - name: Execute Notebook
        shell: bash -l {0}
        run: >
          micromamba activate glider_of_the_day
          && jupyter nbconvert --to notebook --execute gliders_of_the_day.ipynb --output=gliders_of_the_day-output.ipynb

      - name: Publish HTML
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: html/
          keep_files: true
