name: Publish Glider Map of the Day

on:
  pull_request:
  schedule:
    - cron: "0 10 * * *"
  workflow_dispatch:

jobs:
  build:
    name: glider map
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: prefix-dev/setup-pixi@v0.8.1
      - run: pixi run map

      - name: Publish HTML
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: html/
          keep_files: true
