name: Publish Glider Map of the Day

# no permissions by default
permissions: {}

on:
  pull_request:
  schedule:
    - cron: "0 10 * * *"
  workflow_dispatch:

jobs:
  build:
    name: glider map
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: prefix-dev/setup-pixi@a09b6247153796b190642a2b53fac4241043cf6f  # v0.10.0
      - run: pixi run map

      - name: Publish HTML
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453  # v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: html/
          keep_files: true
